---
  kind: pipeline
  name: main

  steps:
    - name: Build updated images
      image: ruby:2.6.5
      volumes:
        - name: docker
          path: /var/run/docker.sock
      environment:
        REGISTRY_USER:
          from_secret: ow_registry_username
        REGISTRY_PASSWORD:
          from_secret: ow_registry_password
      commands:
        - bundle install
        - curl -fsSL https://get.docker.com | bash
        - usermod -a -G docker root
        - docker login reg.openware.work -u $REGISTRY_USER -p $REGISTRY_PASSWORD
        - ./ow-cli incremental-build --push

  volumes:
    - name: docker
      host:
        path: /var/run/docker.sock
  trigger:
  event:
    - push
