version: '3'

services:
  mainet:
    image: quay.io/openware/tron:2.1.1
    environment:
      defaultBalance: '100000'
      showQueryString: 'true'
      showBody: 'true'
      formatJson: 'true'
    ports:
      - 9090:9090
    volumes:
      - ./conf/mainet.conf:/tron/FullNode/fullnode.conf

  testnet:
    image: quay.io/openware/tron:2.1.1
    environment:
      showQueryString: 'true'
      showBody: 'true'
      formatJson: 'true'
    ports:
      - 9090:9090
    volumes:
      - ./conf/testnet.conf:/tron/FullNode/fullnode.conf